export const FETCH_MARQUES_REQUEST = "FETCH_MARQUES_REQUEST";
export const FETCH_MARQUES_SUCCESS = "FETCH_MARQUES_SUCCESS";
export const FETCH_MARQUES_FAILED = "FETCH_MARQUES_FAILED";

export const SAVE_MARQUES_REQUEST = "SAVE_MARQUES_REQUEST";
export const SAVE_MARQUES_SUCCESS = "SAVE_MARQUES_SUCCESS";
export const SAVE_MARQUES_FAILED = "SAVE_MARQUES_FAILED";

export const EDIT_MARQUES_REQUEST = "EDIT_MARQUES_REQUEST";
export const EDIT_MARQUES_SUCCESS = "EDIT_MARQUES_SUCCESS";
export const EDIT_MARQUES_FAILED = "EDIT_MARQUES_FAILED";


export const FETCH_FILTER_SUCCESS = "FETCH_FILTER_SUCCESS";
export const RECHERCHE_SUCCESS = "RECHERCHE_SUCCESS";

